version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: expense-tracker-bot
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - DEBUG
    restart: unless-stopped
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: expense-tracker-worker
    env_file:
      - .env
    environment:
      - DEBUG
    restart: unless-stopped
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:alpine
    container_name: expense-tracker-redis
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
