version: '3.8'

services:
  expense-tracker-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker-bot
    ports:
      - "8001:8000"
    env_file:
      - .env
    restart: unless-stopped
